[Auto-generated] Check & update dependencies (`pyproject.toml`) (#204)
* Update dependencies in `pyproject.toml`

* Update pyproject.toml

* Upgrade to use latest versions as minimum in pyproject

* Update CI test with live backend

Update Dockerfile

* Don't use --target for docker run

* Install coverage if build arg CI is 1.

* Remove trailing comma

* Run apt-get as sudo

* Fix health check for service

* Update to use new pytest marker for mocked hosts

* Fix "Collect coverage" step in CI

* Use absolute paths for coverage

* Report if failing to collect coverage

* Use SIGTERM instead and sleep 10 seconds

---------

Co-authored-by: Casper Welzel Andersen <43357585+CasperWA@users.noreply.github.com>
Co-authored-by: Casper Welzel Andersen <casper.w.andersen@sintef.no>

diff --git a/.github/workflows/ci_tests.yml b/.github/workflows/ci_tests.yml
--- a/.github/workflows/ci_tests.yml
+++ b/.github/workflows/ci_tests.yml
@@ -54,7 +54,7 @@ jobs:
       ENTITIES_SERVICE_CA_FILE: docker_security/test-ca.pem
       # These are used in the Dockerfile as well as in pytest
       ENTITIES_SERVICE_HOST: localhost
-      ENTITIES_SERVICE_PORT: 8000
+      ENTITIES_SERVICE_PORT: 7000
 
     steps:
       - name: Checkout ${{ github.repository }}
@@ -83,15 +83,41 @@ jobs:
             --volume "${{ github.workspace }}/docker_security:/mongo_tls" \
             mongo:8 \
             --tlsMode allowTLS --tlsCertificateKeyFile /mongo_tls/test-server1.pem --tlsCAFile /mongo_tls/test-ca.pem
-          sleep 10  # Wait for the database to start
+
+          # Health check
+          tmp_file=.dockerPs
+          while ! docker exec mongo mongosh --eval "db.runCommand('ping').ok" mongodb://root:root@localhost:27017/?authSource=admin --quiet ; do
+            docker ps -a > $tmp_file
+            grep -E "^.*mongo .* Exited .*$" $tmp_file && exited=yes && break
+            sleep 3
+          done
+          rm -f $tmp_file
+
+          # Write logs
+          docker logs mongo
+
+          if [ -n "$exited" ]; then
+            exit 1
+          fi
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
 
       - name: Build Docker image
-        run: |
-          docker build \
-            --pull \
-            --tag entities-service \
-            --target ${{ matrix.docker_target }} \
-            .
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          target: ${{ matrix.docker_target }}
+          load: true
+          tags: entities-service
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          provenance: false
+          build-args: |
+            CI=1
 
       - name: Install test dependencies
         run: |
@@ -106,20 +132,37 @@ jobs:
           touch -a logs/entities_service.log
 
           # Run the service in the background
-          docker run --rm -d \
+          docker run -d \
             --env ENTITIES_SERVICE_MONGO_URI \
             --env ENTITIES_SERVICE_X509_CERTIFICATE_FILE \
             --env ENTITIES_SERVICE_CA_FILE \
-            --env PORT=${ENTITIES_SERVICE_PORT} \
-            --env RUN_TIME=60 \
-            --env STOP_TIME=3 \
             --name "entities-service" \
             --network "host" \
             --volume "${PWD}:/app" \
-            --entrypoint "./.github/utils/coverage_entrypoint.sh" \
+            --user "$(id -u):$(id -g)" \
+            --init \
+            --entrypoint "gunicorn" \
             entities-service \
-            ${{ matrix.docker_target }}
-          sleep 5  # Wait for the service to start
+            --bind="0.0.0.0:${ENTITIES_SERVICE_PORT}" --workers=1 --worker-class="uvicorn.workers.UvicornWorker" --log-level="debug" --pythonpath=".github/utils" run_with_coverage:APP
+
+          # Install requirements for health check
+          sudo apt-get update && sudo apt-get install -y --no-install-recommends -fqqy curl
+
+          # Health check
+          tmp_file=.dockerPs
+          while ! curl -sf http://localhost:${ENTITIES_SERVICE_PORT}/openapi.json >> /dev/null ; do
+            docker ps -a > $tmp_file
+            grep -E "^.*entities-service .* Exited .*$" $tmp_file && exited=yes && break
+            sleep 1
+          done
+          rm -f $tmp_file
+
+          # Write logs
+          docker logs entities-service
+
+          if [ -n "$exited" ]; then
+            exit 1
+          fi
 
       - name: Run tests
         run: |
@@ -137,20 +180,30 @@ jobs:
 
       - name: Collect coverage
         run: |
-          # We have mapped the current working directory with the service's working
-          # directory in Docker. This means that we can, first of all, stop the service
-          # via a file touch, and then collect the coverage data from the service.
-          #
-          # See the .github/utils/coverage_entrypoint.sh file for more details on the
-          # stopping mechanism.
-          touch stop_gunicorn
+          # We can stop the service via a SIGINT signal.
+          # Since we map the current directory to /app in the container, the coverage file will be
+          # available in the current working directory.
+          docker kill --signal=SIGTERM entities-service
 
-          sleep 3  # Wait for the service to stop
+          # Wait for the coverage file to be written and the service to stop
+          sleep 10
 
-          mv .coverage .coverage.pytest
-          coverage combine --data-file=.coverage.final --rcfile=pyproject.toml .coverage.pytest .coverage.docker
-          coverage xml --data-file=.coverage.final --rcfile=pyproject.toml -o coverage.xml
-          coverage report --data-file=.coverage.final --rcfile=pyproject.toml --show-missing --skip-covered --skip-empty
+          # Combine the coverage data from pytest and the service
+          {
+            mv .coverage .coverage.pytest &&
+            coverage combine --data-file=.coverage.final --rcfile=pyproject.toml .coverage.pytest .coverage.docker &&
+            coverage xml --data-file=.coverage.final --rcfile=pyproject.toml -o coverage.xml &&
+            coverage report --data-file=.coverage.final --rcfile=pyproject.toml --show-missing --skip-covered --skip-empty
+          } || {
+            echo "Failed to collect coverage data." &&
+            echo "Here's the Docker logs for the service:" &&
+            docker logs entities-service &&
+
+            echo -e "\nAnd the service log:" &&
+            cat logs/entities_service.log &&
+
+            exit 1
+          }
 
       - name: Upload coverage
         if: github.repository_owner == 'SINTEF'
@@ -164,6 +217,14 @@ jobs:
         env:
           OS: ubuntu-latest
           PYTHON: '3.10'
+
+      - name: Clean up Docker
+        if: always()
+        run: |
+          docker stop entities-service ||:
+          docker rm entities-service ||:
+          docker stop mongo ||:
+          docker rm mongo ||:
 
   pytest:
     runs-on: ubuntu-latest
